### ISSUE TITLE
import fails on v0.12.0

### ISSUE THREAD

**Issue by thielepaul** [sbtinstruments/asyncio-mqtt#102]
when I import asyncio_mqtt, I get the following error

```
>>> import asyncio_mqtt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/asyncio_mqtt/__init__.py", line 3, in <module>
    from .client import Client, Will, ProtocolVersion
  File "/usr/local/lib/python3.9/site-packages/asyncio_mqtt/client.py", line 89, in <module>
    class Client:
  File "/usr/local/lib/python3.9/site-packages/asyncio_mqtt/client.py", line 248, in Client
    async def subscribe(self, *args: Any, timeout: int = 10, **kwargs: Any) -> int:
TypeError: _outgoing_call() missing 1 required positional argument: 'func'

```

**Comment by frederikaalund** [comment]
Thank you for this quick report. :+1:  I just released v0.12.1 that fixes this issue. Please try to upgrade to v0.12.1. Sorry for the inconvenience.
