### ISSUE TITLE
To narrow calls get a "asyncio_mqtt.error.MqttCodeError: [code:4] The client is not currently connected."

### ISSUE THREAD

**Issue by Soleg06** [sbtinstruments/asyncio-mqtt#171]
Hi, I'm writing code that does MQTT publish message but with a delay.
It seems that if i do theese async request to near in time it will generate the error above.

my testcode:
```python
import asyncio
import arrow
import json
import asyncio_mqtt as aiomqtt
from pprint import pprint


async def sendMqttOnTime(name, device, action, duration):
    
    print(f'{arrow.now().format("YYYY-MM-DD HH:mm:ss")} {name} sceduled')
    await asyncio.sleep(duration)
    print(f'{arrow.now().format("YYYY-MM-DD HH:mm:ss")} {name} done sleeping')
    
    async with aiomqtt.Client(hostname="localhost", client_id="Test") as client:
        await client.publish(f"Test/{device}", json.dumps({
            "state": action,
            "timestamp": arrow.now().format("YYYY-MM-DD HH:mm:ss")}))


async def main():
    print(f"Started {arrow.now().format('YYYY-MM-DD HH:mm:ss')}")
    
    asyncio.create_task(sendMqttOnTime(name="test1", device="one", action="on", duration=5))
    asyncio.create_task(sendMqttOnTime(name="test2", device="two", action="off", duration=5))
    asyncio.create_task(sendMqttOnTime(name="test3", device="three", action="dim", duration=5))
    
    while True:
        await asyncio.sleep(0.01)
    
asyncio.run(main())

```
In this example i submit three tasks with waiting time of 5 sec each. 
This is the output:

```python
Started 2022-12-24 00:33:10
2022-12-24 00:33:10 test1 sceduled
2022-12-24 00:33:10 test2 sceduled
2022-12-24 00:33:10 test3 sceduled
2022-12-24 00:33:15 test1 done sleeping
2022-12-24 00:33:15 test2 done sleeping
2022-12-24 00:33:15 test3 done sleeping
Task exception was never retrieved
future: <Task finished name='Task-4' coro=<sendMqttOnTime() done, defined at /home/staffan/ReturnpathUtv/Mqtt_Eventloop/testasynciorunlater.py:11> exception=MqttCodeError('Unexpected disconnect')>
Traceback (most recent call last):
  File "/home/staffan/ReturnpathUtv/Mqtt_Eventloop/testasynciorunlater.py", line 18, in sendMqttOnTime
    await client.publish(f"Test/{device}", json.dumps({
  File "/usr/local/lib/python3.9/dist-packages/asyncio_mqtt/client.py", line 114, in decorated
    return await method(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/asyncio_mqtt/client.py", line 466, in publish
    raise MqttCodeError(info.rc, "Could not publish message")
asyncio_mqtt.error.MqttCodeError: [code:4] The client is not currently connected.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/staffan/ReturnpathUtv/Mqtt_Eventloop/testasynciorunlater.py", line 18, in sendMqttOnTime
    await client.publish(f"Test/{device}", json.dumps({
  File "/usr/local/lib/python3.9/dist-packages/asyncio_mqtt/client.py", line 837, in __aexit__
    raise disc_exc
asyncio_mqtt.error.MqttCodeError: [code:7] The connection was lost.
Task exception was never retrieved
future: <Task finished name='Task-3' coro=<sendMqttOnTime() done, defined at /home/staffan/ReturnpathUtv/Mqtt_Eventloop/testasynciorunlater.py:11> exception=MqttCodeError('Unexpected disconnect')>
Traceback (most recent call last):
  File "/home/staffan/ReturnpathUtv/Mqtt_Eventloop/testasynciorunlater.py", line 18, in sendMqttOnTime
    await client.publish(f"Test/{device}", json.dumps({
  File "/usr/local/lib/python3.9/dist-packages/asyncio_mqtt/client.py", line 114, in decorated
    return await method(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/asyncio_mqtt/client.py", line 466, in publish
    raise MqttCodeError(info.rc, "Could not publish message")
asyncio_mqtt.error.MqttCodeError: [code:4] The client is not currently connected.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/staffan/ReturnpathUtv/Mqtt_Eventloop/testasynciorunlater.py", line 18, in sendMqttOnTime
    await client.publish(f"Test/{device}", json.dumps({
  File "/usr/local/lib/python3.9/dist-packages/asyncio_mqtt/client.py", line 837, in __aexit__
    raise disc_exc
asyncio_mqtt.error.MqttCodeError: [code:7] The connection was lost.
```
However, if I increase the time so that they don't happen at the same time, it works but not always.

```python
async def main():
    print(f"Started {arrow.now().format('YYYY-MM-DD HH:mm:ss')}")
    
    asyncio.create_task(sendMqttOnTime(name="test1", device="one", action="on", duration=5))
    asyncio.create_task(sendMqttOnTime(name="test2", device="two", action="off", duration=6))
    asyncio.create_task(sendMqttOnTime(name="test3", device="three", action="dim", duration=7))
    
    while True:
        await asyncio.sleep(0.01)
    
asyncio.run(main())
```

This is the correct output:

```python
Started 2022-12-24 00:47:37
2022-12-24 00:47:37 test1 sceduled
2022-12-24 00:47:37 test2 sceduled
2022-12-24 00:47:37 test3 sceduled
2022-12-24 00:47:42 test1 done sleeping
2022-12-24 00:47:43 test2 done sleeping
2022-12-24 00:47:44 test3 done sleeping
```
And it sends the MQTT messages okay. But this fails sometimes too. So I increased the time again to 5, 10, and 15 seconds to get a code that doesn't crash.

I think this must be an issue/bug?

**Comment by frederikaalund** [comment]
Hi Soleg06, thanks for opening this issue. Let me have a look. :)

That's an interesting test case! I have to admit that it took me a while to wrap my head around this issue but I think that I found the culprit:

```python
async with aiomqtt.Client(hostname="localhost", client_id="Test") as client:
```

Here, you use the same `client_id` for all three `Client` instances. Therefore, the server is unable to distinguish between the clients (since they use the same ID). In fact, the server only thinks that there is a *single* client and not three. So as soon as the "first" client sends it's disconnect command, the other clients' publish commands fail.

Try to use a unique `client_id` for each client and see if that works. If not, then let me know and I'll try to have another look at the issue. :)

**Comment by Soleg06** [comment]
Thanks frederikaalund! 
Using unique client_id worked! I tried omitting client_id all together which also worked but I think it will be safer to state a unique id myself.

I also forgot to user asyncio.wait() in my testcode which caused some other concerns but that is totally on me :)

**Comment by frederikaalund** [comment]
Great to hear that it solved the issue for you. :) 👍 I'll close this issue then.
