### ISSUE TITLE
Non-thread-sage operation invoked on an event loop other than the current one

### ISSUE THREAD

**Issue by SimplicityGuy** [sbtinstruments/asyncio-mqtt#52]
When enabling asyncio debugging (via: `PYTHONASYNCIODEBUG=1`), in my code I keep getting this error.

```python
2021-03-11 03:35:55 ERROR Caught exception in on_socket_open: Non-thread-safe operation invoked on an event loop other than the current one
2021-03-11 03:35:55 ERROR Connection to MQTT closed.
Traceback (most recent call last):
  File "/code/listener.py", line 184, in mqtt_engine
    await mqtt_handling()
  File "/code/listener.py", line 151, in mqtt_handling
    await stack.enter_async_context(client)
  File "/usr/local/lib/python3.9/contextlib.py", line 556, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/usr/local/lib/python3.9/site-packages/asyncio_mqtt/client.py", line 324, in __aenter__
    await self.connect()
  File "/usr/local/lib/python3.9/site-packages/asyncio_mqtt/client.py", line 79, in connect
    await loop.run_in_executor(None, self._client.connect, self._hostname, self._port, 60)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1117, in reconnect
    self._call_socket_open()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2071, in _call_socket_open
    self.on_socket_open(self, self._userdata, self._sock)
  File "/usr/local/lib/python3.9/site-packages/asyncio_mqtt/client.py", line 303, in _on_socket_open
    self._misc_task = self._loop.create_task(self._misc_loop())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 748, in call_soon
    self._check_thread()
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 785, in _check_thread
    raise RuntimeError(
RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
2021-03-11 03:35:55 ERROR Task was destroyed but it is pending!
source_traceback: Object created at (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 912, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 77, in _worker
    work_item.run()
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1117, in reconnect
    self._call_socket_open()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 2071, in _call_socket_open
    self.on_socket_open(self, self._userdata, self._sock)
  File "/usr/local/lib/python3.9/site-packages/asyncio_mqtt/client.py", line 303, in _on_socket_open
    self._misc_task = self._loop.create_task(self._misc_loop())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 433, in create_task
    task = tasks.Task(coro, loop=self, name=name)
task: <Task pending name='Task-13' coro=<Client._misc_loop() running at /usr/local/lib/python3.9/site-packages/asyncio_mqtt/client.py:318> created at /usr/local/lib/python3.9/asyncio/base_events.py:433>
```

My code is nearly identical to that of the `advanced_example`, here's a snippet:

```python
async def mqtt_handling():
    async with AsyncExitStack() as stack:
        tasks = set()
        stack.push_async_callback(cancel_tasks, tasks)

        logger.info(f"Connecting to MQTT Broker: {MQTT}.")
        random_id = uuid4().hex
        client = Client(
            MQTT,
            port=8883,
            username=MQTT_USERNAME,
            password=MQTT_PASSWORD,
            client_id=f"{base_listener}-{random_id}",
            tls_context=create_default_context(),
            logger=logger,
        )
        await stack.enter_async_context(client)             # <-- THIS IS LINE 151
        logger.info(f"Connection to {MQTT} open.")

        topic_filters = (
            top1_filter,
            topic2_filter,
            topic3_filter,
        )
        for topic_filter in topic_filters:
            manager = client.filtered_messages(topic_filter)
            messages = await stack.enter_async_context(manager)
            tasks.add(create_task(process_topic(messages, topic_filter)))

        await client.subscribe(f"{base_listener_topic}/#")
        logger.info(f"Listening for messages on {base_listener_topic}/# at {MQTT}.")

        await gather(*tasks)


async def cancel_tasks(tasks):
    for task in tasks:
        if task.done():
            continue
        task.cancel()
        try:
            await task
        except CancelledError:
            pass


async def mqtt_engine():
    while True:
        try:
            await mqtt_handling()
        except MqttError as e:
            logger.error(f"Connection to MQTT closed: {str(e)}")
        except Exception:
            logger.exception("Connection to MQTT closed.")
        finally:
            await sleep(3)


if __name__ == "__main__":
    basicConfig(
        level=INFO,
        format="%(asctime)s %(levelname)s %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    run(mqtt_engine())
```

This is really got me stumped.

**Comment by frederikaalund** [comment]
Thanks for this issue report. Let me have a look. :)

I just tried to run the advanced example with:
 * Python 3.8
 * asyncio-mqtt at the latest commit on the master branch (4b2579add5e2b050ab680cd2ac10a0f95d9b9a8e).
 * PYTHONASYNCIODEBUG=1 set

I don't get an errors at all. What happens if you do the above on your system? With no other changes to the advanced example, that is.

**Comment by SimplicityGuy** [comment]
Same, no issues with advanced example.

However, I suspect that there may be an issue here when using the additional options in the `Client` ctor.

**Comment by frederikaalund** [comment]
Thanks for the follow-up. I think that this is a duplicate of #39. Can you try with the master branch version of asyncio-mqtt?

**Comment by SimplicityGuy** [comment]
Indeed it is! This is a duplicate of #39. Fixes are looking good on my end. Thanks for the info!
