### ISSUE TITLE
Not working in windows

### ISSUE THREAD

**Issue by Trance-Paradox** [sbtinstruments/asyncio-mqtt#66]
OS - WIndows 10
Python - 3.9.5
asyncio-mqtt - 0.9.1

```
Caught exception in on_socket_open: 
Traceback (most recent call last):
  File "d:\#CODE\Python\mqtt.py", line 8, in <module>
    asyncio.run(main())
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete      
    return future.result()
  File "d:\#CODE\Python\mqtt.py", line 5, in main
    async with Client("test.mosquitto.org") as client:
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncio_mqtt\client.py", line 512, in __aenter__
    await self.connect()
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncio_mqtt\client.py", line 173, in connect        
    await loop.run_in_executor(
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\site-packages\paho\mqtt\client.py", line 941, in connect
    return self.reconnect()
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\site-packages\paho\mqtt\client.py", line 1117, in reconnect        
    self._call_socket_open()
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\site-packages\paho\mqtt\client.py", line 2071, in _call_socket_open
    self.on_socket_open(self, self._userdata, self._sock)
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncio_mqtt\client.py", line 467, in _on_socket_open
    self._loop.add_reader(sock.fileno(), cb)
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
Caught exception in on_socket_close: 
Exception ignored in: <function Client.__del__ at 0x0000029A16F06EE0>
Traceback (most recent call last):
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\site-packages\paho\mqtt\client.py", line 660, in __del__
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\site-packages\paho\mqtt\client.py", line 704, in _reset_sockets     
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\site-packages\paho\mqtt\client.py", line 698, in _sock_close        
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\site-packages\paho\mqtt\client.py", line 2105, in _call_socket_close
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\site-packages\asyncio_mqtt\client.py", line 482, in _on_socket_close
  File "C:\Users\surya\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 507, in remove_reader
NotImplementedError: 
```

**Comment by frederikaalund** [comment]
Hi, thanks for your issue report. Let me have a look. :)

Looks like you use the `ProactorEventLoop`. asyncio-mqtt doesn't support this event loop. Try to use the `SelectorEventLoop` instead. See [this section of the readme for more details](https://github.com/sbtinstruments/asyncio-mqtt#note-for-windows-users).

I hope that helps.

**Comment by Trance-Paradox** [comment]
Does asyncio on linux runs `SelectorEventLoop`?

**Comment by frederikaalund** [comment]
Yes, that's the default event loop on Linux. :) On Windows, you have to explicitly select it.

**Comment by Trance-Paradox** [comment]
OK thanks.
I hope implantations for the shortcoming on windows get sorted out by python on later releases
