### ISSUE TITLE
Does not work with Python 3.9?

### ISSUE THREAD

**Issue by iudeen** [sbtinstruments/asyncio-mqtt#94]
The code I used:
```python
import asyncio
import json

from asyncio_mqtt import Client, ProtocolVersion


async def main():
    async with Client(hostname="192.168.0.220", port=1883, protocol=ProtocolVersion.V31) as client:
        message = {"state": 3}
        await client.publish(
            "floors/bed_room/humidity",
            payload=json.dumps(message)
        )


asyncio.run(main())
```

Traceback:

```text
Caught exception in on_socket_open: 
Traceback (most recent call last):
  File "G:\My Drive\PycharmProjects\ilens-core\iLensVisualization4\eee.py", line 21, in <module>
    asyncio.run(main())
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "G:\My Drive\PycharmProjects\ilens-core\iLensVisualization4\eee.py", line 9, in main
    async with Client(hostname="192.168.0.220", port=1883, protocol=ProtocolVersion.V31) as client:
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\site-packages\asyncio_mqtt\client.py", line 526, in __aenter__
    await self.connect()
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\site-packages\asyncio_mqtt\client.py", line 186, in connect
    await loop.run_in_executor(
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\site-packages\paho\mqtt\client.py", line 914, in connect
    return self.reconnect()
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\site-packages\paho\mqtt\client.py", line 1086, in reconnect
    self._call_socket_open()
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\site-packages\paho\mqtt\client.py", line 2155, in _call_socket_open
    on_socket_open(self, self._userdata, self._sock)
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\site-packages\asyncio_mqtt\client.py", line 481, in _on_socket_open
    self._loop.add_reader(sock.fileno(), cb)
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\asyncio\events.py", line 504, in add_reader
    raise NotImplementedError
NotImplementedError
Caught exception in on_socket_close: 
Exception ignored in: <function Client.__del__ at 0x000001F94A019940>
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\site-packages\paho\mqtt\client.py", line 636, in __del__
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\site-packages\paho\mqtt\client.py", line 675, in _reset_sockets
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\site-packages\paho\mqtt\client.py", line 668, in _sock_close
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\site-packages\paho\mqtt\client.py", line 2200, in _call_socket_close
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\site-packages\asyncio_mqtt\client.py", line 496, in _on_socket_close
  File "D:\ProgramData\Anaconda3\envs\iLensVisualization4\lib\asyncio\events.py", line 507, in remove_reader
NotImplementedError: 
```

What might be the issue?

**Comment by frederikaalund** [comment]
Hi iudeen,

On Windows, you have to manually change the event loop. See: https://github.com/sbtinstruments/asyncio-mqtt#note-for-windows-users

~Frederik

**Comment by frederikaalund** [comment]
It's been a month now. I assume that this was due to the default event loop on Windows. :) I'll reopen this issue if there are new developments.
